services:
  cassandra:
    image: 'cassandra:latest'
    container_name: "cassandra"
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra/data
    networks:
      - app-tier-compose-network

volumes:
  cassandra-data:

networks: 
  app-tier-compose-network:
    driver: bridge
